# Generated by Django 4.2.1 on 2023-06-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Image_Path', models.CharField(max_length=255)),
                ('Price_Rs', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=50)),
                ('Owner_Name', models.CharField(max_length=100)),
                ('No_Bathrooms', models.IntegerField()),
                ('No_Bedrooms', models.IntegerField()),
                ('Map_Location', models.CharField(max_length=255)),
                ('Agent_Email', models.CharField(max_length=255)),
                ('Property_Type', models.CharField(max_length=100)),
                ('Agent_Phone', models.BigIntegerField()),
                ('Size_sqft', models.IntegerField()),
                ('Vacant_Rooms', models.IntegerField()),
                ('No_Floors', models.IntegerField()),
            ],
        ),
    ]
